replicaCount: 2

image:
  repository: tree12/gitops-demo-app
  tag: bd4f927
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: true
  host: ci-cd.local
  tls:
    enabled: true
    secretName: ci-cd-tls

rollout:
  canary:
    steps:
      - setWeight: 20
      - pause:
          duration: 30s
      - setWeight: 50
      - pause:
          duration: 30s
      - setWeight: 100
      - pause:
          duration: 30s
