apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "gitops-demo.fullname" . }}
  labels:
    app: {{ include "gitops-demo.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "gitops-demo.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "gitops-demo.name" . }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
  strategy:
    canary:
      steps:
{{ toYaml .Values.rollout.canary.steps | indent 8 }}
