apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitops-demo.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "gitops-demo.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      protocol: TCP
