apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ci-cd-app-ingress
  namespace: ci-cd
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - ci-cd.local
    secretName: ci-cd-tls
  rules:
  - host: ci-cd.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ci-cd-service
            port:
              number: 5000
