{
 "title": "CI/CD App Observability",
 "tags": [
  "ci-cd",
  "app",
  "observability",
  "k8s"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "App Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "rate(flask_request_count[1m])", "legendFormat": "requests/sec" }
   ]
  },
  {
   "title": "App Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"ci-cd-app\"}",
     "legendFormat": "up"
    }
   ]
  },
  {
   "title": "Request Latency (5m avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg_over_time(flask_request_latency_seconds[5m])",
     "legendFormat": "avg latency"
    }
   ]
  },
  {
   "title": "Node CPU Load (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "sum(node_load1) by (instance)", "legendFormat": "load1 {{instance}}" }
   ]
  },
  {
   "title": "Pods per Namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(kube_pod_info) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Available Deployment Replicas by Namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "StatefulSet Replica Count by Namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(kube_statefulset_status_replicas) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  }
 ]
}